name = "Hugo blog newcss"
license = "MIT"
licenselink = "https://github.com/Permanently/hugo-blog-newcss/blob/main/LICENSE"
description = "Minimal Hugo blog theme that implements new.css"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/Permanently/hugo-blog-newcss/"

tags = ["blog", "responsive", "minimal", "dark", "light", "multilingual"]
features = ["blog", "sass", "dark"]

min_version = "0.87.0"

# If the theme has a single author
[author]
    name = "Permanently"
    homepage = "https://github.com/Permanently"
